#!/bin/sh
source /opt/dftoolkit/bin/activate
STUDY=$1
shift
STUDYDIR=`/opt/dfdiscover/bin/DFgetparam.rpc -s $STUDY STUDY_DIR`
if [ -z "$STUDYDIR" ]
then
    echo "Unable to determine STUDY_DIR for study $STUDY"
    exit 2
fi

OUTPUT=$STUDYDIR/work/eclist.xlsx

EClist --studydir $STUDYDIR --xlsx $OUTPUT

if [ $? -eq 0 ]
then
    echo "Output file is $OUTPUT"
else
    echo "Report terminated with errors."
    exit 2
fi

